theme: jekyll-theme-minima
title: Tyler Russell - Mechanisms Portfolio
description: Engineering mechanisms and designs

header_pages:
  - index.md
  - About Me/About me.md
  - Project Overview.md
  - Mechanism/Four-Bar Linkage.md
  - Mechanism/Geneva.md
  - Mechanism/Scotch Yoke.md
