site_name: Engineering in Motion Final Project Site
theme:
  name: null
  custom_dir: 'cinder'
  colorscheme: 'Cinder Superhero'
nav:
  - Home: index.md
  - About Me: About Me/About me.md
  - Project Overview: Project Overview.md
  - Mechanisms:
      - Four-Bar Linkage: Mechanism/Four-Bar Linkage.md
      - Geneva: Mechanism/Geneva.md
      - Scotch Yoke: Mechanism/Scotch Yoke.md
