site_name: Engineering in Motion Final Project Site
theme:
  name: null
  custom_dir: 'cinder'
  colorscheme: 'monokai'
nav:
  - Home: index.md
  - About Me: About me.md
  - Section 2:
      - Subpage A: subpageA.md
      - Subpage B: subpageB.md
  - Another Page: another-page.md